language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "4.0"
  - "4.2"
  - "5.0"
env:
  - NODE_ENV=development
services:
  - mongodb

before_install:
  - npm i -g bower

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/08c84711c36e875930d0
      - https://hooks.slack.com/services/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
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # default: false


